### ISSUE TITLE
Controller或Action不存在时程序报错退出

### ISSUE THREAD

**Issue by leizongmin** [75team/thinkjs#162]
操作步骤：

+ 使用命令 `$ thinkjs xxx` 创建的项目
+ 进入`xxx`目录，执行 `$ node www`
+ 用浏览器访问`http://127.0.0.1:8360/aaa` （肯定不存在相应的页面）

控制台报错，进程退出：

```
Server running at http://127.0.0.1:8360/
Error: Controller `Aaa` not found. pathname is `aaa`
    at Object.App.exec (/Users/glen/work/tmp/a/node_modules/thinkjs/lib/Lib/Core/App.js:163:15)
    at /Users/glen/work/tmp/a/node_modules/thinkjs/lib/Lib/Core/App.js:325:18
    at runMicrotasksCallback (node.js:337:7)
    at process._tickDomainCallback (node.js:381:11)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at /Users/glen/work/tmp/a/node_modules/thinkjs/lib/Lib/Core/Http.js:377:24
    at runMicrotasksCallback (node.js:337:7)
    at process._tickDomainCallback (node.js:381:11)
```

当前所使用的版本为 `thinkjs@1.2.2`

**Comment by leizongmin** [comment]
经调试，问题出在这里:

```javascript
App.sendError = function(http, error){
  'use strict';
  if (!error) {
    return;
  }
  var message = isError(error) ? error.stack : error;
  console.error(message);
  if (!http.res) {
    return;
  }
  http.res.statusCode = C('error_code') || 500;
  http.setHeader('Content-Type', 'text/html; charset=' + C('encoding'));
  if (APP_DEBUG) {
    http.echo(message);
    http.end();
  }else{
    var readStream = fs.createReadStream(C('error_tpl_path'));
    readStream.pipe(http.res);
    readStream.on('end', function(){
      http.end();
    });
  }
}
```

如果当前为调试模式，执行

```javascript
http.echo(message);
http.end();
```

但实际上 `http.end()` 中的 `res.end()` 的执行顺序先于 `http.echo()` 中的 `res.write()`，故报错 `Error: write after end`。

后将该部分代码改为：

```javascript
http.echo('<pre>' + message + '</pre>').then(function () {
  http.end();
});
```

此时程序没有保存退出，而是显示网页：

```
Error: Controller `Aaa` not found. pathname is `aaa`
    at Object.App.exec (/Users/glen/work/sites/appmarket/node_modules/thinkjs/lib/Lib/Core/App.js:163:15)
    at /Users/glen/work/sites/appmarket/node_modules/thinkjs/lib/Lib/Core/App.js:328:18
    at runMicrotasksCallback (node.js:337:7)
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by welefen** [comment]
多谢，你可以form下项目 然后发个pr
