### ISSUE TITLE
实时编译报错

### ISSUE THREAD

**Issue by xuexb** [75team/thinkjs#195]
使用`es7`的`async`后发现当`npm start`并开启`实时编译`功能后，当`web`页面被访问时，再保存文件后报错：

```
[2015-11-12 10:52:09] [BABEL] compile file home/controller/index.js error
[2015-11-12 10:52:09] [Error] Error: unknown:
    at new Scope (/Users/baidu/work/github/blog/node_modules/thinkjs/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/scope.js:15:15)
    at NodePath.NPp._computeScope (/Users/baidu/work/github/blog/node_modules/thinkjs/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/node-path.js:116:17)
```

由于编译失败了，保存的内容也不会实时的生效，即`web`访问页面不会更改～

使用的版本为：

```json
"dependencies": {
    "thinkjs": "^2.0.6",
    "babel": "5.8.21",
    "babel-runtime": "5.6.17"
}
```

**Comment by qgy18** [comment]
是的，现在编译出错缺乏一个通知机制。刷新页面使用的是之前编译的结果，所以很难发现编译出问题。
如果是 Mac，倒是可以在编译出错时，调用系统的 notification。

**Comment by welefen** [comment]
已经修复，下个版本会更新

1、编译出错后会直接显示错误页面
2、修复了 Babel 有时候会出现异常的问题（和自动更新机制干扰相关）
