### ISSUE TITLE
模板配置prerender报错

### ISSUE THREAD

**Issue by xuexb** [75team/thinkjs#197]
复制文档里`视图`里的代码片段，并修改`type`为`nunjucks`，按文档里添加了`prerender`过滤器，如：

```js
export default {
    type: 'nunjucks',
    content_type: 'text/html',
    file_ext: '.html',
    file_depr: '_',
    root_path: think.ROOT_PATH + '/view',
    prerender: function (nunjucks, env) {
        //添加一个过滤器，这样可以在模板里使用了
        env.addFilter("filter_foo", function () {
            return 'x';
        });
    },
    options: {}
};
```

但浏览页面时会报错，如：

```
[2015-11-13 23:14:01] [Error] TypeError: Cannot read property 'addFilter' of undefined
    at Object.prerender (/Users/baidu/work/github/blog/app/common/config/view.js:13:12)
    at _default.prerender (/Users/baidu/work/github/blog/node_modules/thinkjs/lib/adapter/template/base.js:63:24)
    at _default.run$ (/Users/baidu/work/github/blog/node_modules/thinkjs/lib/adapter/template/ejs.js:53:16)
    at tryCatch (/Users/baidu/work/github/blog/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:67:40)
```

但发现页面还是正确的渲染了，经观察，发现`prerender`的方法被调用了2次，其中第一次是被`nunjucks`调用了，第二次是被`ejs`调用了

运行环境 node v4.2.1：

```json
"dependencies": {
    "thinkjs": "^2.0.6",
    "babel": "5.8.21",
    "babel-runtime": "5.6.17"
}
```

**Comment by welefen** [comment]
升级到 2.0.7 版本看下还是否有这个问题

**Comment by xuexb** [comment]
2.0.7修改配置后没有该问题～

**Comment by xuexb** [comment]
@welefen thinkjs升级到2.1.3访问404文件时又报这个错误了～ [test](https://xuexb.com/test)

**Comment by xuexb** [comment]
经测试发现必须添加个空的`ejs.prerender`方法访问404页面时才不会报错，不然就还会报`[2015-11-13 23:14:01] [Error] TypeError: Cannot read property 'addFilter' of undefined`错误～

```js
export default {
    type: 'nunjucks',
    root_path: think.ROOT_PATH + '/view',
    adapter: {
        ejs: {
            prerender: () => {}
        },
        nunjucks: {
            prerender: (nunjucks, env) => {
                // 美化时间
                env.addFilter('elapsed', (date, str) => {
                    return Util.parseDate.elapsed(date, str);
                });

                // 日期格式化
                env.addFilter('format', (date, str) => {
                    return Util.parseDate.format(date, str);
                });
            }
        }
    }
};
```

**Comment by welefen** [comment]
@xuexb  因为之前错误页面强制用 ejs 模板渲染的，所以需要在 `prerender` 里判断下 env 变量。

最新版已经改了，不在使用 ejs 渲染。你可以重新创建个项目，然后把对应的错误代码拷贝过去。
