### ISSUE TITLE
mysql like报错

### ISSUE THREAD

**Issue by xuexb** [75team/thinkjs#198]
控制器代码：

```js
async searchAction() {
    let key = this.param('key').trim();
    let page = this.param('page');

    let data = await this.model('article').order('id DESC').where({
        title: ['like', '%' + key + '%']
    }).page(page).countSelect({}, false);

    return this.json(data);
}
```

访问`/index/search?key=n`时正确，日志如：

```
[2015-11-14 17:44:58] [SQL] SELECT COUNT(article.id) AS think_count FROM `article` WHERE ( `title` LIKE '%n%' ) ORDER BY id DESC LIMIT 1 2ms
[2015-11-14 17:44:58] [SQL] SELECT * FROM `article` WHERE ( `title` LIKE '%n%' ) ORDER BY id DESC LIMIT 0,10 14ms
```

当访问`key=nn`或者`key=#$%^&*`时报错，日志是：

```
2015-11-14 17:45:42] [SQL] SELECT COUNT(article.id) AS think_count FROM `article` WHERE ( `title` LIKE '%nn%' ) ORDER BY id DESC LIMIT 1 8ms
[2015-11-14 17:45:42] [SQL] SELECT * FROM `article` WHERE ( `title` LIKE '%nn%' ) ORDER BY id DESC LIMIT -10,10 6ms
[2015-11-14 17:45:42] [Error] Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-10,10' at line 1
    at Query.Sequence._packetToError (/Users/baidu/work/github/blog/node_modules/thinkjs/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/baidu/work/github/blog/node_modules/thinkjs/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/baidu/work/github/blog/node_modules/thinkjs/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/Users/baidu/work/github/blog/node_modules/thinkjs/node_modules/mysql/lib/protocol/Parser.js:77:12)
```

但这样写在`1.x`时是没问题的，且敏感字符会自动过滤。

运行环境：
```json
"dependencies": {
    "thinkjs": "^2.0.8",
    "babel": "5.8.21",
    "babel-runtime": "5.6.17"
}
```

**Comment by welefen** [comment]
确定为 count 为 0， limit 出现负数导致的

已经在 2.0.9 版本种修复
