### ISSUE TITLE
--es6 初始化后报错

### ISSUE THREAD

**Issue by airyland** [75team/thinkjs#205]
看到有很多很有用的特性想尝试一下，按照 https://thinkjs.org/zh-CN/doc/2.0/create_project.html 安装执行后，npm start 有很多报错。又试了几次，发现用了--es6的会报错，不用就正常。

```
> thinkjs-application@1.0.0 start E:\workspace\wechat-insight
> node www/development.js

[2015-11-20 14:21:24] [BABEL] compile file common\bootstrap\global.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\bootstrap\middleware.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\config\config.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\config\db.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\config\env\development.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\config\env\production.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\config\env\testing.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\config\hook.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\config\locale\en.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\config\session.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\config\view.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file common\controller\error.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file home\config\config.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file home\controller\base.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file home\controller\index.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file home\logic\index.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [BABEL] compile file home\model\index.js error
[2015-11-20 14:21:24] [Error] SyntaxError: E:\workspace\package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:100:62)
    at OptionManager.findConfigs (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (E:\workspace\wechat-insight\node_modules\thinkjs\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at _default.compileFile (E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:75:24)
    at E:\workspace\wechat-insight\node_modules\thinkjs\lib\util\watch_compile.js:159:26
    at Array.forEach (native)
[2015-11-20 14:21:24] [THINK] Server running at http://127.0.0.1:8360/
[2015-11-20 14:21:24] [THINK] ThinkJS Version: 2.0.9
[2015-11-20 14:21:24] [THINK] Cluster Status: closed
[2015-11-20 14:21:24] [THINK] WebSocket Status: closed
[2015-11-20 14:21:24] [THINK] File Auto Compile: true
[2015-11-20 14:21:24] [THINK] File Auto Reload: true
[2015-11-20 14:21:24] [THINK] App Enviroment: development

```

**Comment by welefen** [comment]
从错误上看是 `package.json` 这个文件有格式错误，我这边回归了下都是正常的。

请提供下 package.json 文件的内容以及你当前的 Node 和 npm 版本

**Comment by airyland** [comment]
node v5.0.0

注意一下报错的package.json路径，我是在 /workspace/wechat-insight下执行的 npm start ,为什么会报 /workspace/package.json 的格式错误？

**Comment by airyland** [comment]
我把workspace/package.json 这个空的文件移除确实正常了。疑惑的是，thinkjs为什么会读取这个package.json?
