### ISSUE TITLE
thinkjs 2.1.0 多级 Controller 添加失败

### ISSUE THREAD

**Issue by AlphaTr** [75team/thinkjs#240]
thinkjs 2.1.0  在 `normal ` 模式下，添加多级 controller 报 404 错误，错误信息如下

```
Error: controller `api/user` not found. url is `/api/user`.
    at _class.execController (/develop/web/cloud-bookmark/node_modules/thinkjs/lib/core/app.js:167:18)
    at /develop/web/cloud-bookmark/node_modules/thinkjs/lib/core/app.js:119:21
    at tryCatcher (/develop/web/cloud-bookmark/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:11:23)
...
```

文件目录如下：
```
├── controller
│   ├── api
│   │   ├── base.js
│   │   └── user.js
│   ├── base.js
│   ├── error.js
│   └── index.js
```

**Comment by welefen** [comment]
已经修复

**Comment by Z-starts** [comment]
thinkjs是否支持这种路由呢？
![image](https://cloud.githubusercontent.com/assets/1948235/12443322/06cd370c-bf92-11e5-84f6-32c558f28401.png)

访问方式：http://localhost:8360/api/v1/gdasapi/ 
http://localhost:8360/api/gdasapi/

**Comment by welefen** [comment]
`src/common/config/route.js` 里:

```js
export default [
  [/^api\/gdasapi(.*)$/, 'api/v1/gdasapi:1']
]
```
