### ISSUE TITLE
建议在Model中添加Mongo的collection populate 方法

### ISSUE THREAD

**Issue by zl810881283** [75team/thinkjs#244]
MongoDB有的时候还是需要表关联的，希望可以实现mongoose 中的 populate ，这个在实际项目中非常好用

**Comment by welefen** [comment]
会在下个较大版本里考虑，整个 Model 会进行一次重写，到时候 Mongo 会支持 populate

**Comment by grapewheel** [comment]
@zl810881283 支持楼主，不想用mongoose，要绑定model麻烦，现在只能重复find来替换

**Comment by sunwu7096** [comment]
问下大家,iisnode部署时如何解决这个问题:
Application has thrown an uncaught exception and is terminated:
Error: write ENOTSUP
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.target._send (internal/child_process.js:668:20)
    at ChildProcess.target.send (internal/child_process.js:552:19)
    at sendHelper (cluster.js:753:15)
    at send (cluster.js:535:12)
    at cluster.js:510:7
    at SharedHandle.add (cluster.js:99:3)
    at queryServer (cluster.js:502:12)
    at Worker.onmessage (cluster.js:451:7)
    at ChildProcess.<anonymous> (cluster.js:767:8)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:758:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
