### ISSUE TITLE
ThinkJS 2.1日志问题

### ISSUE THREAD

**Issue by denniswlin** [75team/thinkjs#267]
使用ThinkJS 2.1版本新建一个项目，启动后就报如下这样的日志，非常多以至于正常的日志都受到影响，有什么办法没？

Warning: a promise was created in a handler but was not returned from it
    at D:\jsplus\SVN\pad_web_group_website\Node\project\pa18-dms\node_modules\thinkjs\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
    at Object.statusAction (D:\jsplus\SVN\pad_web_group_website\Node\project\pa18-dms\node_modules\thinkjs\lib\core\think.js:1190:16)
    at _class.execError (D:\jsplus\SVN\pad_web_group_website\Node\project\pa18-dms\node_modules\thinkjs\lib\core\app.js:262:18)
    at D:\jsplus\SVN\pad_web_group_website\Node\project\pa18-dms\node_modules\thinkjs\lib\core\app.js:287:16
From previous event:
    at _class.run (D:\jsplus\SVN\pad_web_group_website\Node\project\pa18-dms\node_modules\thinkjs\lib\core\app.js:286:24)
    at D:\jsplus\SVN\pad_web_group_website\Node\project\pa18-dms\node_modules\thinkjs\lib\core\app.js:305:26
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Server.callback (D:\jsplus\SVN\pad_web_group_website\Node\project\pa18-dms\node_modules\thinkjs\lib\core\app.js:304:28)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

**Comment by welefen** [comment]
这个表示有 Promise 没有处理 catch，下个版本准备去除这个提示

**Comment by xsy233** [comment]
thinkjs 2.1.6
类似的问题

目前只能在`src/common/bootstrap`中添加
`process.on('unhandledRejection', () => {});`
来解决

**Comment by denniswlin** [comment]
@xsy233 你是怎么加的，能贴下代码吗？

**Comment by xsy233** [comment]
@denniswlin 
```js
// src/common/bootstrap/global.js
process.on('unhandledRejection', () => {});
```

**Comment by welefen** [comment]
已经在 2.1.7 版本中修复

**Comment by denniswlin** [comment]
@welefen 
我看2.1.7更新日志中已经修复了，我更2.2.1后，新创建的项目，还是有如下提示，是需要设置什么吗？

Warning: a promise was created in a handler but was not returned from it
    at D:\jsplus\SVN\node\pa18-trace\node_modules\thinkjs\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
    at Object.statusAction (D:\jsplus\SVN\node\pa18-trace\node_modules\thinkjs\src\core\think.js:947:22)
    at _class.execError (D:\jsplus\SVN\node\pa18-trace\node_modules\thinkjs\src\core\app.js:169:18)
    at D:\jsplus\SVN\node\pa18-trace\node_modules\thinkjs\src\core\app.js:191:14
From previous event:
    at _class.run (D:\jsplus\SVN\node\pa18-trace\node_modules\thinkjs\src\core\app.js:190:7)
    at D:\jsplus\SVN\node\pa18-trace\node_modules\thinkjs\src\core\app.js:206:24
    at processImmediate [as _immediateCallback] (timers.js:383:17)
