### ISSUE TITLE
import src之外的路径下面的文件报错

### ISSUE THREAD

**Issue by winnieBear** [75team/thinkjs#363]
## DESC
我在controller里引入自己写的模块，该模块不是在src目录下，而是在src之外的目录下，执行的时候就报错：
[2016-06-01 14:44:43] [Error] SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module._load (module.js:300:12)
    at Function.sys_module._load (e:\proj\topic\node_modules\thinkjs\lib\util\auto_reload.js:196:24)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (e:\proj\topic\app\home\controller\index.js:15:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module._load (module.js:300:12)
    at Function.sys_module._load (e:\proj\topic\node_modules\thinkjs\lib\util\auto_reload.js:196:24)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

 如果这个模块文件在src下面就不报错，src外面就报错，请问怎么引用src之外的模块。
## ENV

Platform:
windows

Node.js Version:4.4
ThinkJS Version:2.2.3

**Comment by welefen** [comment]
src 之前的文件不会用 Babel 编译，需要需要引用的需要自己编译。

另：如果是独立与项目之外，那就弄成一个 npm 模块吧

**Comment by winnieBear** [comment]
非常赞成银的反馈速度，多谢！

**Comment by welefen** [comment]
src 之外的需要自己用 Babel 编译下
