### ISSUE TITLE
编辑代码保存后报错 no such file or directory, open 'src/admin/controller/index.js'

### ISSUE THREAD

**Issue by xiaoyann** [75team/thinkjs#390]
## DESC
刚创建的项目，所有文件编辑后保存时都报这种错误 o(╯□╰)o:

```
Error: ENOENT: no such file or directory, open 'src/admin/controller/index.js'
```

```
[2016-07-11 14:37:54] [Babel] Compile file admin/controller/index.js 23ms
Error: ENOENT: no such file or directory, open 'src/admin/controller/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.compile (/Users/xiaoyan/working/52dachu/node_modules/babel-cli/lib/babel/util.js:60:19)
    at write (/Users/xiaoyan/working/52dachu/node_modules/babel-cli/lib/babel/dir.js:24:21)
    at handleFile (/Users/xiaoyan/working/52dachu/node_modules/babel-cli/lib/babel/dir.js:47:7)
    at FSWatcher.<anonymous> (/Users/xiaoyan/working/52dachu/node_modules/babel-cli/lib/babel/dir.js:92:15)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:188:7)
    at FSWatcher.<anonymous> (/Users/xiaoyan/working/52dachu/node_modules/chokidar/index.js:191:15)
Error: ENOENT: no such file or directory, open 'src/admin/controller/index.js'
```

## ENV

Platform: Mac

Node.js Version: 6.3.0

NPM Version: 3.10.3

ThinkJS Version: 2.2.5

**Comment by welefen** [comment]
那看下有这个文件么？

**Comment by xiaoyann** [comment]
有，就是因为有才问的

**Comment by welefen** [comment]
这个问题已经解决了？

**Comment by xiaoyann** [comment]
我重新 new 了一个项目没问题，就把 issue 关了，可能是我的环境有问题吧

**Comment by welefen** [comment]
OK
