### ISSUE TITLE
mac 编译错误

### ISSUE THREAD

**Issue by jmying** [75team/thinkjs#411]
2016-08-02 10:05:31] [Error] ReferenceError: [BABEL] home/model/index.js: Using removed Babel 5 option: /Users/jinmouyang/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/jinmouyang/job/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/jinmouyang/job/node_modules/babel-core/lib/transformation/file/options/option-manager.js:233:20)
    at OptionManager.init (/Users/jinmouyang/job/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
    at File.initOptions (/Users/jinmouyang/job/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/jinmouyang/job/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/jinmouyang/job/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at _class.compileByBabel (/Users/jinmouyang/job/node_modules/thinkjs/lib/util/watch_compile.js:192:22)
    at _class.compileFile (/Users/jinmouyang/job/node_modules/thinkjs/lib/util/watch_compile.js:103:14)
    at /Users/jinmouyang/job/node_modules/thinkjs/lib/util/watch_compile.js:325:26
    at Array.forEach (native)
    at _class.compile (/Users/jinmouyang/job/node_modules/thinkjs/lib/util/watch_compile.js:303:11)
    at _class.run (/Users/jinmouyang/job/node_modules/thinkjs/lib/util/watch_compile.js:359:10)
    at _class.compile (/Users/jinmouyang/job/node_modules/thinkjs/lib/index.js:521:14)
    at Object.<anonymous> (/Users/jinmouyang/job/www/development.js:15:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by welefen** [comment]
是因为 `/Users/jinmouyang/.babelrc.stage` 这个文件影响的，删了应该就好了。

**Comment by jmying** [comment]
好了，谢谢
