### ISSUE TITLE
大概过5-6个小时就会出现500 error

### ISSUE THREAD

**Issue by Jerret321** [75team/thinkjs#423]
## DESC
错误日志
```
Android-Update-5 (err):     at Object.think.await (/home/web/Android-Update/node_modules/thinkjs/lib/core/think.js:1021:25)
Android-Update-5 (err):     at _class._callee$ (/home/web/Android-Update/node_modules/thinkjs/lib/adapter/socket/mysql.js:142:54)
Android-Update-5 (err):     at tryCatch (/home/web/Android-Update/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:88:40)
Android-Update-5 (err):     at GeneratorFunctionPrototype.invoke [as _invoke] (/home/web/Android-Update/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:341:22)
Android-Update-5 (err):     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/web/Android-Update/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:121:21)
Android-Update-5 (err):     at step (/home/web/Android-Update/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
Android-Update-5 (err):     at /home/web/Android-Update/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
Android-Update-5 (err):     at tryCatcher (/home/web/Android-Update/node_modules/bluebird/js/release/util.js:16:23)
Android-Update-5 (err):     at Promise._settlePromiseFromHandler (/home/web/Android-Update/node_modules/bluebird/js/release/promise.js:502:31)
Android-Update-5 (err):     at Promise._settlePromise (/home/web/Android-Update/node_modules/bluebird/js/release/promise.js:559:18)
Android-Update-5 (err):     at Promise._settlePromiseCtx (/home/web/Android-Update/node_modules/bluebird/js/release/promise.js:596:10)
Android-Update-5 (err):     at Async._drainQueue (/home/web/Android-Update/node_modules/bluebird/js/release/async.js:143:12)
Android-Update-5 (err):     at Async._drainQueues (/home/web/Android-Update/node_modules/bluebird/js/release/async.js:148:10)
Android-Update-5 (err):     at Immediate.Async.drainQueues [as _onImmediate] (/home/web/Android-Update/node_modules/bluebird/js/release/async.js:17:14)
Android-Update-5 (err): [2016-08-10 05:48:19] [Error] Error: Connection reset. http://www.thinkjs.org/doc/error_message.html#econnreset
Android-Update-5 (err):     at exports._errnoException (util.js:860:11)
Android-Update-5 (err):     at TCP.onread (net.js:544:26)
Android-Update-5 (err): [2016-08-11 05:16:37] [Error] Error: Connection reset. http://www.thinkjs.org/doc/error_message.html#econnreset
Android-Update-5 (err):     at exports._errnoException (util.js:860:11)
Android-Update-5 (err):     at TCP.onread (net.js:544:26)
```
重启pm2后又好了，但是会重复规律的出现上面的问题。

## ENV

Platform: centos 65

Node.js Version: 5.0.0

ThinkJS Version: 3.3.6

**Comment by Jerret321** [comment]
问答社区也有同样的问题：http://wenda.thinkjs.org/?/question/132

**Comment by llqgit** [comment]
5～6小时！你比我们这个精确多了，兄弟。
我们这两天发现是一晚上过后就 Down 掉了，我们以为是 **mysql** 数据库的问题，应该是改了配置了，但是还是有这个现象。不知道是不是和你一样。

**Comment by Jerret321** [comment]
@llqgit 是这样的

**Comment by Jerret321** [comment]
测试下 这位同学的解决方案 [pull#425](https://github.com/75team/thinkjs/pull/425)

**Comment by Jerret321** [comment]
貌似更新了新版好了很多。 在观察下 如果还是正常就关闭了。
