### ISSUE TITLE
mongodb replicaSet 副本集设置

### ISSUE THREAD

**Issue by llqgit** [75team/thinkjs#480]
## DESC

在进行 mongodb 数据库 ```replicaSet``` 配置的时候报错，配置如下：
```
 export default {
  type: 'mongo',
  adapter: {
    mongo: {
      host: [
        '172.31.123.123',
        '172.31.123.124'
      ],
      port: [
        '27017',
        '27017'
      ],
      database: 'testdb',
      user: 'root',
      password: 'password',
      prefix: 'ch_',
      encoding: 'utf8',
      options: {
        authSource: 'admin',
        replicaSet: 'test'
      }
    }
  }
};
```

```
Error: mongodb://root:password@172.31.123.123:27017,172.31.123.124:27017/testdb?authSource=admin&replicaSet=test
    at /work/project/chcms/node_modules/thinkjs/src/adapter/socket/mongo.js:79:17
    at _class.run (/work/project/chcms/node_modules/thinkjs/src/util/await.js:31:30)
    at Object.think.await (/work/project/chcms/node_modules/thinkjs/src/core/think.js:856:25)
    at _class._callee$ (/work/project/chcms/node_modules/thinkjs/src/adapter/socket/mongo.js:59:18)
    at tryCatch (/work/project/chcms/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/work/project/chcms/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/work/project/chcms/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:121:21)
    at step (/work/project/chcms/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /work/project/chcms/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
    at tryCatcher (/work/project/chcms/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/work/project/chcms/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/work/project/chcms/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/work/project/chcms/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/work/project/chcms/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/work/project/chcms/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/work/project/chcms/node_modules/bluebird/js/release/async.js:17:14)
```

不知道是哪儿错误了

## ENV

Platform: mac os

Node.js Version: 6.2.2

ThinkJS Version: 2.2.13

**Comment by im-kulikov** [comment]
how to reproduce?

**Comment by llqgit** [comment]
I can not get any data normally from the mongodb, when I run the db code and connect mongodb the error will come up.
By the way, this ```Error: ......``` message is **console.log** from the ```node_module/thinkjs/lib/core/thinkjs.js  line_num:1114``` which I have added.
@im-kulikov

**Comment by im-kulikov** [comment]
@llqgit hm.. i try to reproduce, but without any data it will be harder

**Comment by im-kulikov** [comment]
@llqgit can you try to connect from pure nodejs:

```js
var MongoClient = require('mongodb').MongoClient,
    assert = require('assert');

MongoClient.connect('mongodb://root:password@172.31.123.123:27017,172.31.123.124:27017/testdb?authSource=admin&replicaSet=test', function(err, db) {
  assert.equal(null, err);
  assert.ok(db != null);

  // check if there any errors
});
```

**Comment by llqgit** [comment]
Danke  :P 
There is A error indeed when I run your code on my server.
And it looks like this:
```
> AssertionError: null == EventEmitter {
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxLis
    at repl:1:149
    at connectCallback (/work/test/test_mongo_node/node_modules/mongodb/lib/mongo_client.js:315:5)
    at /work/test/test_mongo_node/node_modules/mongodb/lib/mongo_client.js:222:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
> 
```
I don't know what's the hell is that. It's confused me a lot. And I got no idea how to deal with it. I need helpppppppp.

By the way, I just give you a format IP of my code, because the connection must from our specific server, otherwise it can't connect basically. And the error message is A real.

**Comment by im-kulikov** [comment]
@llqgit are you trying to connect manually? i suppose it can be error in configuration of mongodb or bug of mongo-driver

**Comment by llqgit** [comment]
Hey man. I finally got the reason why this error happened. @im-kulikov 
The reason is my npm package version;
when the package ```mongodb``` version is ```2.0.48``` everything is OK.
But when the version is ```2.2.10``` that error happened.

And even the native node, when I just install the package ```mongodb``` it also the same like this.
I still don't know why. But thanks.

**Comment by im-kulikov** [comment]
@llqgit it can be a bug in mongodb driver. You can check what happenes between version 2.0.48 and 2.2.10, and make PR or issue to this package.

**Comment by llqgit** [comment]
OK.

**Comment by im-kulikov** [comment]
I close this issue?

**Comment by im-kulikov** [comment]
If need, reopen it.
