### ISSUE TITLE
getLineAndCharacterOfPosition undefined

### ISSUE THREAD

**Issue by MiYogurt** [75team/thinkjs#489]
## DESC

```
npm install thinkjs@2 -g
thinkjs new gg --ts
cd gg && npm i
npm start
```

```
[2016-10-23 23:05:25] [COMPILE] compile file common\controller\error.ts error
[2016-10-23 23:05:25] [Error] TypeError: Cannot read property 'getLineAndCharacterOfPosition' of undefined
    at _class.compileByTypeScript (C:\Users\yugo\gg\node_modules\thinkjs\lib\util\watch_compile.js:157:56)
    at _class.compileFile (C:\Users\yugo\gg\node_modules\thinkjs\lib\util\watch_compile.js:99:14)
    at C:\Users\yugo\gg\node_modules\thinkjs\lib\util\watch_compile.js:323:26
    at Array.forEach (native)
    at _class.compile (C:\Users\yugo\gg\node_modules\thinkjs\lib\util\watch_compile.js:301:11)
    at _class.run (C:\Users\yugo\gg\node_modules\thinkjs\lib\util\watch_compile.js:357:10)
    at _class.compile (C:\Users\yugo\gg\node_modules\thinkjs\lib\index.js:520:14)
    at Object.<anonymous> (C:\Users\yugo\gg\www\development.js:15:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

why ？

老的项目就没问题，新的就有问题，我改了以前项目的依赖也不行。

Previously created the project is no problem, the new project will be a problem

## ENV

Platform: Win10

Node.js Version: 6.7.0

ThinkJS Version: 2.2.13

TypeScript Version: 2.0.3

**Comment by MiYogurt** [comment]
Sorry!My hand is out of control !
对不起,是我手贱!
第一次编译的时候，绝对不要输错代码。
```
  /**
   * index action
   * @return {Promise} []
   */
  indexAction(){
    //auto render template file index_index.html
    this.assign({});
    return this.display();
  }

```

**Comment by MiYogurt** [comment]
今天又遇见了这个问题，好像不是代码问题，是编译的依赖问题。
it look like fsevents problem, not my code reason.

```
[fsevents@1.0.14] download from binary mirror: {"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"https://npm.taobao.org/mirrors/fsevents"}
[fsevents@1.0.14](.\node_modules\.1.6.1@chokidar\node_modules\fsevents) unsupported: Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
```

**Comment by MiYogurt** [comment]
```
// modify your package.json
--     "typescript": "next",
++     "typescript": "2.0.3",
```

**Comment by im-kulikov** [comment]
Can you make PR?

**Comment by welefen** [comment]
It's already changed typescript dependency version to 2.0.3 when create application, but in previous project, you need change version by yourself.
